### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by darwintree**
Complete contract caller and contract event functionalities and tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/4)

### CODE REVIEW

**Review by Pana — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 9 of 9 files at r3, 5 of 5 files at r4, 9 of 9 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @darwintree)

**Review by Pana — CHANGES_REQUESTED** [review]
> Reviewed 17 of 21 files at r8, 8 of 8 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/4)* status: all files reviewed, 2 unresolved discussions (waiting on @darwintree)

___
*[`conflux_web3/client.py` line 769 at r10](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/4#-NAs78es6uaJiYLsHgJG:-NAs78et9KOgOMe0hYoI:b-ts0vfc) ([raw file](https://github.com/conflux-chain/python-conflux-sdk/blob/c6f90990be9bb19c5a2e8e192e24b1ac35298ba5/conflux_web3/client.py#L769)):*
> ```Python
>         return self._get_vote_list(address, block_identifier)
>     
>     def get_interst_rate(
> ```

There is a typo here 
___
*[`conflux_web3/txpool.py` line 7 at r10](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/4#-NAs7axJ3kAFFxoquFHC:-NAs7axJ3kAFFxoquFHD:bh4q90d) ([raw file](https://github.com/conflux-chain/python-conflux-sdk/blob/c6f90990be9bb19c5a2e8e192e24b1ac35298ba5/conflux_web3/txpool.py#L7)):*
> ```Python
> 
> class Txpool(Module):
>     _nextNonce = ConfluxMethod(
> ```

The name style here is not camel case

**Review by darwintree — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/4)* status: 24 of 44 files reviewed, 2 unresolved discussions (waiting on @Pana)

___
*[`conflux_web3/client.py` line 769 at r10](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/4#-NAs78es6uaJiYLsHgJG:-NAxCtjh064WMEY6HuDv:b-896fix) ([raw file](https://github.com/conflux-chain/python-conflux-sdk/blob/c6f90990be9bb19c5a2e8e192e24b1ac35298ba5/conflux_web3/client.py#L769)):*
<details><summary><i>Previously, Pana (Pana) wrote…</i></summary><blockquote>

There is a typo here 
</blockquote></details>

Done.
___
*[`conflux_web3/txpool.py` line 7 at r10](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/4#-NAs7axJ3kAFFxoquFHC:-NAxCwUMDYOzzWlP5LZd:b-896fix) ([raw file](https://github.com/conflux-chain/python-conflux-sdk/blob/c6f90990be9bb19c5a2e8e192e24b1ac35298ba5/conflux_web3/txpool.py#L7)):*
<details><summary><i>Previously, Pana (Pana) wrote…</i></summary><blockquote>

The name style here is not camel case
</blockquote></details>

Done.

**Review by Pana — APPROVED** [review]
> Reviewed 20 of 20 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @darwintree)

**Pull request merged**
