### PR TITLE
Support Drip/GDrip/CFX as token units

### PR DESCRIPTION
**Pull request by darwintree**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/10)

### CODE REVIEW

**Review by Pana — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/10)* status: all files reviewed, 1 unresolved discussion (waiting on @darwintree)

___
*[`conflux_web3/client.py` line 497 at r1](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/10#-NEsVq7l2clMLPib8HUN:-NEsVq7l2clMLPib8HUO:b3gexek) ([raw file](https://github.com/conflux-chain/python-conflux-sdk/blob/613276303a70f9f70130826eec5baef1f1797057/conflux_web3/client.py#L497)):*
> ```Python
>                     address: AddressParam, 
>                     block_identifier: Optional[EpochNumberParam] = None) -> CFX:
>         return self._get_balance(address, block_identifier).to(CFX)
> ```

why change the unit to CFX, it better to keep align with RPC return and other SDK

**Review by darwintree — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/10)* status: all files reviewed, 1 unresolved discussion (waiting on @Pana)

___
*[`conflux_web3/client.py` line 497 at r1](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/10#-NEsVq7l2clMLPib8HUN:-NEu2B2D5cK0sa3C6fi_:b-hxji5y) ([raw file](https://github.com/conflux-chain/python-conflux-sdk/blob/613276303a70f9f70130826eec5baef1f1797057/conflux_web3/client.py#L497)):*
<details><summary><i>Previously, Pana (Pana) wrote…</i></summary><blockquote>

why change the unit to CFX, it better to keep align with RPC return and other SDK
</blockquote></details>

This behaviour provides better readability for developers. 
Returned value as drip provides little readability, and new developer might be confused by the representation of token with 18 decimals. Convert the returned balance to CFX hides these details.
Token unit classes such as CFX, GDrip, and Drip aim to provide a simple and safe mechanism to operate with assets, in some way like Move language.  It is desired that a developer won't feel any difference between using CFX(1) or Drip(10**18) except for representation form

However, currently the token unit implementation might bring about incompatibility or potential safety problem if token unit objects are operated with a variable without a unit. For example, currently it is allowed to do operation like `CFX(1) + 1` or `CFX(1) < 2`. These are designed as grammar candy for the convienience to operate token units. It is under consideration to forbid such kind of behaviour and only `CFX(1).value + 1` and `CFX(1).value < 2 ` is allowed, which means the developer is only allowed to safe operation on token units.

**Review by darwintree — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/10)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @Pana)

___
*[`conflux_web3/client.py` line 497 at r1](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/10#-NEsVq7l2clMLPib8HUN:-NF8Z01z2sH6D5cFpUpW:bz4llry) ([raw file](https://github.com/conflux-chain/python-conflux-sdk/blob/613276303a70f9f70130826eec5baef1f1797057/conflux_web3/client.py#L497)):*
<details><summary><i>Previously, darwintree wrote…</i></summary><blockquote>

This behaviour provides better readability for developers. 
Returned value as drip provides little readability, and new developer might be confused by the representation of token with 18 decimals. Convert the returned balance to CFX hides these details.
Token unit classes such as CFX, GDrip, and Drip aim to provide a simple and safe mechanism to operate with assets, in some way like Move language.  It is desired that a developer won't feel any difference between using CFX(1) or Drip(10**18) except for representation form

However, currently the token unit implementation might bring about incompatibility or potential safety problem if token unit objects are operated with a variable without a unit. For example, currently it is allowed to do operation like `CFX(1) + 1` or `CFX(1) < 2`. These are designed as grammar candy for the convienience to operate token units. It is under consideration to forbid such kind of behaviour and only `CFX(1).value + 1` and `CFX(1).value < 2 ` is allowed, which means the developer is only allowed to safe operation on token units.
</blockquote></details>

Recovered

**Review by Pana — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @darwintree)

**Review by Pana — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @darwintree)

**Pull request merged**
