### PR TITLE
Fix web3 contract constructor build_transaction compatibility problem

### PR DESCRIPTION
**Pull request by darwintree**
Fix web3 contract constructor build_transaction compatibility problem
Add 2 examples

- - -
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/5)

### CODE REVIEW

**Review by Pana — CHANGES_REQUESTED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/5)* status: all files reviewed, 1 unresolved discussion (waiting on @darwintree)

___
*[`.github/workflows/test.yml` line 10 at r1](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/5#-NBoq4rf25BmAp-6MCUc:-NBoq4rf25BmAp-6MCUd:bcsaeri) ([raw file](https://github.com/conflux-chain/python-conflux-sdk/blob/e67b4a17af2b8cf22259245e0998720d81b996ee/.github/workflows/test.yml#L10)):*
> ```YAML
>     branches: [ "dev", "v1" ]
>   # pull_request:
>   #   branches: [ "v2" ]
> ```

This line can be removed

**Review by darwintree — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/5)* status: 23 of 58 files reviewed, 1 unresolved discussion (waiting on @Pana)

___
*[`.github/workflows/test.yml` line 10 at r1](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/5#-NBoq4rf25BmAp-6MCUc:-NC4TsQY60of5z8FH2u3:b-896fix) ([raw file](https://github.com/conflux-chain/python-conflux-sdk/blob/e67b4a17af2b8cf22259245e0998720d81b996ee/.github/workflows/test.yml#L10)):*
<details><summary><i>Previously, Pana (Pana) wrote…</i></summary><blockquote>

This line can be removed 
</blockquote></details>

Done.

**Review by Pana — CHANGES_REQUESTED** [review]
> Reviewed 35 of 35 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/5)* status: all files reviewed, 3 unresolved discussions (waiting on @darwintree)

___
*[`conflux_web3/contract/metadata/__init__.py` line 24 at r2](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/5#-NCIJ11WBeylBtYBa_GS:-NCIJ11WBeylBtYBa_GT:bl5znv4) ([raw file](https://github.com/conflux-chain/python-conflux-sdk/blob/27eb3fbf4150825bc9dc5e45ed475b138d9f002b/conflux_web3/contract/metadata/__init__.py#L24)):*
> ```Python
>     "SponsorWhitelistControl": "0x0888000000000000000000000000000000000001",
>     "Staking": "0x0888000000000000000000000000000000000002",
>     "ConfluxContext": "0x0888000000000000000000000000000000000003",
> ```

ConfluxContext is only used in Solidity 
___
*[`conflux_web3/contract/metadata/ParamsControl.json` line 4 at r2](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/5#-NCIIU2hEiNQsqrzB_Jn:-NCIIU2hEiNQsqrzB_Jo:b-c9rlwy) ([raw file](https://github.com/conflux-chain/python-conflux-sdk/blob/27eb3fbf4150825bc9dc5e45ed475b138d9f002b/conflux_web3/contract/metadata/ParamsControl.json#L4)):*
> ```JSON
>     "abi": [
>         {
>             "anonymous": false,
> ```

this contract have some update
___
*[`conflux_web3/contract/metadata/SponsorWhitelistControl.json` line 235 at r2](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/5#-NCIIfL24oaldc_2kcFN:-NCIIfL24oaldc_2kcFO:b-3ilpld) ([raw file](https://github.com/conflux-chain/python-conflux-sdk/blob/27eb3fbf4150825bc9dc5e45ed475b138d9f002b/conflux_web3/contract/metadata/SponsorWhitelistControl.json#L235)):*
> ```JSON
>         }
>     ],
>     "bytecode": "608060405234801561001057600080fd5b5061086d806100206000396000f3fe6080604052600436106100c25760003560e01c80638382c3a71161007f578063d2932db611610059578063d2932db61461061d578063d47e9a57146106e2578063d665f9dd14610747578063e66c1bea146107ac576100c2565b80638382c3a71461049e578063b3b28fac1461052f578063b6b3527214610594576100c2565b806310128d3e146100c7578063217e055b1461018c57806322effe841461027157806333a1af31146103565780633e3e6428146103e757806379b47faa14610435575b600080fd5b3480156100d357600080fd5b5061018a600480360360208110156100ea57600080fd5b810190808035906020019064010000000081111561010757600080fd5b82018360208201111561011957600080fd5b8035906020019184602083028401116401000000008311171561013b57600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600081840152601f19601f8201169050808301925050505050505091929192905050506107f0565b005b34801561019857600080fd5b5061026f600480360360408110156101af57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803590602001906401000000008111156101ec57600080fd5b8201836020820111156101fe57600080fd5b8035906020019184602083028401116401000000008311171561022057600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600081840152601f19601f8201169050808301925050505050505091929192905050506107f3565b005b34801561027d57600080fd5b506103546004803603604081101561029457600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803590602001906401000000008111156102d157600080fd5b8201836020820111156102e357600080fd5b8035906020019184602083028401116401000000008311171561030557600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600081840152601f19601f8201169050808301925050505050505091929192905050506107f7565b005b34801561036257600080fd5b506103a56004803603602081101561037957600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291905050506107fb565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b610433600480360360408110156103fd57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919080359060200190929190505050610802565b005b34801561044157600080fd5b506104846004803603602081101561045857600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610806565b604051808215151515815260200191505060405180910390f35b3480156104aa57600080fd5b506104ed600480360360208110156104c157600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919050505061080d565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561053b57600080fd5b5061057e6004803603602081101561055257600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610814565b6040518082815260200191505060405180910390f35b3480156105a057600080fd5b50610603600480360360408110156105b757600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff16906020019092919050505061081b565b604051808215151515815260200191505060405180910390f35b34801561062957600080fd5b506106e06004803603602081101561064057600080fd5b810190808035906020019064010000000081111561065d57600080fd5b82018360208201111561066f57600080fd5b8035906020019184602083028401116401000000008311171561069157600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600081840152601f19601f820116905080830192505050505050509192919290505050610823565b005b3480156106ee57600080fd5b506107316004803603602081101561070557600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610826565b6040518082815260200191505060405180910390f35b34801561075357600080fd5b506107966004803603602081101561076a57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919050505061082d565b6040518082815260200191505060405180910390f35b6107ee600480360360208110156107c257600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610834565b005b50565b5050565b5050565b6000919050565b5050565b6000919050565b6000919050565b6000919050565b600092915050565b50565b6000919050565b6000919050565b5056fea2646970667358221220b153816a8ec2281a39154927e25bb2c4c128bf4b2a6bc3633b32333de0e45b2264736f6c63430006060033"
> ```

bytecode is useless in SDK

**Review by darwintree — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/5)* status: 51 of 60 files reviewed, 3 unresolved discussions (waiting on @Pana)

___
*[`conflux_web3/contract/metadata/__init__.py` line 24 at r2](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/5#-NCIJ11WBeylBtYBa_GS:-NCJXxIW9OF5jIIIO-HQ:b-896fix) ([raw file](https://github.com/conflux-chain/python-conflux-sdk/blob/27eb3fbf4150825bc9dc5e45ed475b138d9f002b/conflux_web3/contract/metadata/__init__.py#L24)):*
<details><summary><i>Previously, Pana (Pana) wrote…</i></summary><blockquote>

ConfluxContext is only used in Solidity 
</blockquote></details>

Done.
___
*[`conflux_web3/contract/metadata/ParamsControl.json` line 4 at r2](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/5#-NCIIU2hEiNQsqrzB_Jn:-NCJXyaq1yhd-WDCnR6Z:b-896fix) ([raw file](https://github.com/conflux-chain/python-conflux-sdk/blob/27eb3fbf4150825bc9dc5e45ed475b138d9f002b/conflux_web3/contract/metadata/ParamsControl.json#L4)):*
<details><summary><i>Previously, Pana (Pana) wrote…</i></summary><blockquote>

this contract have some update
</blockquote></details>

Done.
___
*[`conflux_web3/contract/metadata/SponsorWhitelistControl.json` line 235 at r2](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/5#-NCIIfL24oaldc_2kcFN:-NCJXvu_CUs8HCCJtUY5:b-896fix) ([raw file](https://github.com/conflux-chain/python-conflux-sdk/blob/27eb3fbf4150825bc9dc5e45ed475b138d9f002b/conflux_web3/contract/metadata/SponsorWhitelistControl.json#L235)):*
<details><summary><i>Previously, Pana (Pana) wrote…</i></summary><blockquote>

bytecode is useless in SDK
</blockquote></details>

Done.

**Review by Pana — APPROVED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/python-conflux-sdk/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @darwintree)

**Pull request merged**
